### ISSUE TITLE
Add client/cook selector on SignUp Page

### ISSUE THREAD

**Issue by wiltley** [wiltley/SEG2105-Mealer-Application#14]
For now let's let the user pick whether they are a client or a cook on the sign up page

**Comment by DSL04** [comment]
There is no need, when they sign up they are redirected to welcome page that prompts them which type of user they are, cook or client.

**Comment by DSL04** [comment]
now only thing is the firestore needs to store that input they choose as their role

**Comment by DSL04** [comment]
Solved
